apiVersion: v1
kind: Service
metadata:
  labels:
    env: graph-visuals
  name: grafana-deployment
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30006
  selector:
    env: graph-visuals
  type: NodePort