apiVersion: v1
kind: Service
metadata:
  labels:
    env: metrics
  name: prometheus-deployment
spec:
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30005
  selector:
    env: metrics
  type: NodePort